hr_people_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      user: "{{ env_var('DBT_USER', 'hr_user') }}"
      password: "{{ env_var('DBT_PASSWORD', 'hr_pass') }}"
      port: "{{ env_var('DBT_PORT', '5433') | int }}"
      dbname: "{{ env_var('DBT_DBNAME', 'hr_db') }}"
      schema: public
      threads: 4
